import type { Activity, Badge, Comment, Entry, HelpContribution, Post, User, UserRank } from "./types"

export const userRanks: UserRank[] = [
  { level: 1, title: "Newcomer", color: "text-gray-500", minPoints: 0 },
  { level: 2, title: "Helper", color: "text-green-500", minPoints: 100 },
  { level: 3, title: "Contributor", color: "text-blue-500", minPoints: 500 },
  { level: 4, title: "Champion", color: "text-orange-500", minPoints: 1000 },
  { level: 5, title: "Legend", color: "text-orange-500", minPoints: 2500 },
]

export const badges: Badge[] = [
  {
    id: "1",
    name: "First Giveaway",
    description: "Created your first giveaway",
    icon: "🎁",
    color: "bg-blue-100 text-blue-800",
    earnedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Generous Heart",
    description: "Helped 10 people with their requests",
    icon: "❤️",
    color: "bg-red-100 text-red-800",
    earnedAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "Community Builder",
    description: "Gained 100 followers",
    icon: "🏗️",
    color: "bg-green-100 text-green-800",
    earnedAt: new Date("2024-02-15"),
  },
]

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alex Chen",
    username: "alexchen",
    email: "alex@example.com",
    avatar: "/professional-asian-person.png",
    bio: "Crypto enthusiast and community builder. Love helping others succeed! 🚀",
    walletAddress: "0x1234...5678",
    walletBalance: 2500.75,
    followersCount: 1250,
    followingCount: 340,
    postsCount: 45,
    rank: userRanks[3],
    badges: [badges[0], badges[1], badges[2]],
    joinedAt: new Date("2023-08-15"),
    isVerified: true,
  },
  {
    id: "user-2",
    name: "Sarah Johnson",
    username: "sarahj",
    email: "sarah@example.com",
    avatar: "/friendly-woman-smiling.png",
    bio: "Artist and designer. Creating beautiful things and spreading positivity ✨",
    walletAddress: "0x2345...6789",
    walletBalance: 890.25,
    followersCount: 850,
    followingCount: 200,
    postsCount: 32,
    rank: userRanks[2],
    badges: [badges[0], badges[2]],
    joinedAt: new Date("2023-09-20"),
    isVerified: false,
  },
  {
    id: "user-3",
    name: "Marcus Williams",
    username: "marcusw",
    email: "marcus@example.com",
    avatar: "/confident-black-man.png",
    bio: "Tech entrepreneur. Building the future one project at a time 💻",
    walletAddress: "0x3456...7890",
    walletBalance: 5200.0,
    followersCount: 2100,
    followingCount: 150,
    postsCount: 67,
    rank: userRanks[4],
    badges: badges,
    joinedAt: new Date("2023-06-10"),
    isVerified: true,
  },
  {
    id: "user-4",
    name: "Emma Rodriguez",
    username: "emmar",
    email: "emma@example.com",
    avatar: "/young-latina-woman.png",
    bio: "Student and aspiring developer. Always learning something new! 📚",
    walletBalance: 125.5,
    followersCount: 320,
    followingCount: 450,
    postsCount: 18,
    rank: userRanks[1],
    badges: [badges[0]],
    joinedAt: new Date("2024-01-05"),
    isVerified: false,
  },
  {
    id: "user-5",
    name: "David Kim",
    username: "davidk",
    email: "david@example.com",
    avatar: "/korean-man-glasses.png",
    bio: "Gaming content creator and streamer. Let's play together! 🎮",
    walletAddress: "0x5678...9012",
    walletBalance: 1750.8,
    followersCount: 980,
    followingCount: 280,
    postsCount: 41,
    rank: userRanks[2],
    badges: [badges[0], badges[1]],
    joinedAt: new Date("2023-11-12"),
    isVerified: true,
  },
]

export const mockEntries: Entry[] = [
  {
    id: "1",
    postId: "1",
    userId: "user-2",
    user: mockUsers[1],
    message:
      "Started coding 2 years ago with Python! Currently building a web app for local businesses. @davidk @emmar check this out!",
    submittedAt: new Date("2024-03-11T09:15:00Z"),
    proofUrl: "https://github.com/sarahj/local-business-app",
  },
  {
    id: "2",
    postId: "1",
    userId: "user-5",
    user: mockUsers[4],
    message: "Been coding for 3 years, started with game development! Now working on streaming tools. @emmar @sarahj",
    submittedAt: new Date("2024-03-11T11:30:00Z"),
    proofUrl: "https://github.com/davidk/stream-tools",
  },
  {
    id: "7",
    postId: "1",
    userId: "user-4",
    user: mockUsers[3],
    message: "That's so cool @sarahj! I'm also learning web development. Would love to collaborate sometime!",
    submittedAt: new Date("2024-03-11T10:20:00Z"),
    parentId: "1",
  },
  {
    id: "8",
    postId: "1",
    userId: "user-1",
    user: mockUsers[0],
    message: "@davidk Your streaming tools look amazing! Have you considered open sourcing them?",
    submittedAt: new Date("2024-03-11T12:45:00Z"),
    parentId: "2",
  },
  {
    id: "9",
    postId: "1",
    userId: "user-2",
    user: mockUsers[1],
    message: "@emmar DM me and we can set up a call to discuss ideas 😊",
    submittedAt: new Date("2024-03-11T11:15:00Z"),
    parentId: "7",
  },
  {
    id: "13",
    postId: "1",
    userId: "user-5",
    user: mockUsers[4],
    message: "@alexchen Thanks! We're actually planning to open source it next quarter 🎉",
    submittedAt: new Date("2024-03-11T13:00:00Z"),
    parentId: "8",
  },
  {
    id: "14",
    postId: "1",
    userId: "user-1",
    user: mockUsers[0],
    message: "@davidk That's amazing! Can't wait to contribute 💪",
    submittedAt: new Date("2024-03-11T13:30:00Z"),
    parentId: "13",
  },
  {
    id: "15",
    postId: "1",
    userId: "user-4",
    user: mockUsers[3],
    message: "@sarahj Awesome! I'll definitely reach out, thanks so much! 🙌",
    submittedAt: new Date("2024-03-11T11:45:00Z"),
    parentId: "9",
  },
  {
    id: "3",
    postId: "3",
    userId: "user-4",
    user: mockUsers[3],
    message: "Here's my latest digital art piece! Been working on this cyberpunk series.",
    submittedAt: new Date("2024-03-09T10:20:00Z"),
    proofUrl: "https://artstation.com/emmar/cyberpunk-series",
  },
  {
    id: "10",
    postId: "3",
    userId: "user-2",
    user: mockUsers[1],
    message: "@emmar This is incredible! The color palette is perfect. How long did this take you?",
    submittedAt: new Date("2024-03-09T11:30:00Z"),
    parentId: "3",
  },
  {
    id: "16",
    postId: "3",
    userId: "user-4",
    user: mockUsers[3],
    message: "@sarahj Thank you so much! About 40 hours total. Loved every minute of it! 🎨",
    submittedAt: new Date("2024-03-09T12:00:00Z"),
    parentId: "10",
  },
  {
    id: "17",
    postId: "3",
    userId: "user-2",
    user: mockUsers[1],
    message: "@emmar That dedication is inspiring! Worth every hour 👏",
    submittedAt: new Date("2024-03-09T12:30:00Z"),
    parentId: "16",
  },
  {
    id: "4",
    postId: "4",
    userId: "user-1",
    user: mockUsers[0],
    message: "Just watched the tutorial! Amazing content as always. Here's my attempt at the technique.",
    submittedAt: new Date("2024-03-12T14:20:00Z"),
  },
  {
    id: "5",
    postId: "4",
    userId: "user-3",
    user: mockUsers[2],
    message: "This tutorial helped me so much! Sharing with my team.",
    submittedAt: new Date("2024-03-12T16:45:00Z"),
  },
  {
    id: "11",
    postId: "4",
    userId: "user-2",
    user: mockUsers[1],
    message: "@alexchen Thanks for watching! Your attempt looks great, keep practicing! 🎨",
    submittedAt: new Date("2024-03-12T15:30:00Z"),
    parentId: "4",
  },
  {
    id: "18",
    postId: "4",
    userId: "user-1",
    user: mockUsers[0],
    message: "@sarahj Thanks so much! Really helps having detailed feedback 🙏",
    submittedAt: new Date("2024-03-12T16:00:00Z"),
    parentId: "11",
  },
  {
    id: "19",
    postId: "4",
    userId: "user-3",
    user: mockUsers[2],
    message: "@sarahj Can you share the UI kit link? My team would love to use it!",
    submittedAt: new Date("2024-03-12T17:15:00Z"),
    parentId: "5",
  },
  {
    id: "6",
    postId: "6",
    userId: "user-2",
    user: mockUsers[1],
    message: "Love this gaming setup! The RGB lighting is perfect.",
    submittedAt: new Date("2024-03-13T11:30:00Z"),
  },
  {
    id: "12",
    postId: "6",
    userId: "user-5",
    user: mockUsers[4],
    message: "@sarahj Thanks! Took me months to get the lighting just right. What's your setup like?",
    submittedAt: new Date("2024-03-13T12:15:00Z"),
    parentId: "6",
  },
  {
    id: "20",
    postId: "6",
    userId: "user-2",
    user: mockUsers[1],
    message: "@davidk I'm still using my old MacBook 😅 but I love the setup! Inspiring me to upgrade",
    submittedAt: new Date("2024-03-13T13:00:00Z"),
    parentId: "12",
  },
]

export const mockContributions: HelpContribution[] = [
  {
    id: "1",
    postId: "2",
    userId: "user-1",
    user: mockUsers[0],
    amount: 100,
    currency: "USDC",
    message: "Keep learning and building! You've got this! 💪",
    contributedAt: new Date("2024-03-09T15:45:00Z"),
  },
  {
    id: "7",
    postId: "2",
    userId: "user-4",
    user: mockUsers[3],
    amount: 0,
    currency: "USDC",
    message: "@alexchen Thank you so much! This means everything to me 🙏",
    contributedAt: new Date("2024-03-09T16:00:00Z"),
    parentId: "1",
  },
  {
    id: "2",
    postId: "2",
    userId: "user-3",
    user: mockUsers[2],
    amount: 75,
    currency: "USDC",
    message: "Education is the best investment. Good luck with your studies!",
    contributedAt: new Date("2024-03-09T18:20:00Z"),
  },
  {
    id: "3",
    postId: "2",
    userId: "user-5",
    user: mockUsers[4],
    amount: 50,
    currency: "USDC",
    message: "Every developer needs good tools. Hope this helps!",
    contributedAt: new Date("2024-03-10T08:10:00Z"),
  },
  {
    id: "8",
    postId: "2",
    userId: "user-4",
    user: mockUsers[3],
    amount: 0,
    currency: "USDC",
    message: "@davidk Already looking at some great laptops with these funds 💻",
    contributedAt: new Date("2024-03-10T09:30:00Z"),
    parentId: "3",
  },
  {
    id: "4",
    postId: "2",
    userId: "user-2",
    user: mockUsers[1],
    amount: 20,
    currency: "USDC",
    message: "Small contribution but big support! 🎨",
    contributedAt: new Date("2024-03-10T12:30:00Z"),
  },
  {
    id: "5",
    postId: "5",
    userId: "user-1",
    user: mockUsers[0],
    amount: 200,
    currency: "USDC",
    message: "Mental health is so important. Take care of yourself!",
    contributedAt: new Date("2024-03-11T10:15:00Z"),
  },
  {
    id: "6",
    postId: "5",
    userId: "user-3",
    user: mockUsers[2],
    amount: 150,
    currency: "USDC",
    message: "Therapy changed my life. Hope this helps you too.",
    contributedAt: new Date("2024-03-11T14:30:00Z"),
  },
  {
    id: "9",
    postId: "5",
    userId: "user-5",
    user: mockUsers[4],
    amount: 0,
    currency: "USDC",
    message: "@marcusw That's so encouraging to hear. I'm hopeful this will help me too ❤️",
    contributedAt: new Date("2024-03-11T15:00:00Z"),
    parentId: "6",
  },
]

export const mockComments: Comment[] = [
  {
    id: "1",
    postId: "1",
    userId: "user-2",
    user: mockUsers[1],
    content: "This is amazing! Thanks for supporting new developers 🙏",
    createdAt: new Date("2024-03-10T10:30:00Z"),
    parentId: undefined,
  },
  {
    id: "2",
    postId: "1",
    userId: "user-4",
    user: mockUsers[3],
    content: "Just entered! This community is so supportive ❤️",
    createdAt: new Date("2024-03-10T11:15:00Z"),
    parentId: undefined,
  },
  {
    id: "3",
    postId: "1",
    userId: "user-1",
    user: mockUsers[0],
    content: "Love seeing everyone's coding journeys! Keep building! 🚀",
    createdAt: new Date("2024-03-10T12:00:00Z"),
    parentId: "2",
  },
  {
    id: "4",
    postId: "2",
    userId: "user-3",
    user: mockUsers[2],
    content: "Just contributed! Education should be accessible to everyone 📚",
    createdAt: new Date("2024-03-09T18:25:00Z"),
    parentId: undefined,
  },
  {
    id: "5",
    postId: "3",
    userId: "user-5",
    user: mockUsers[4],
    content: "These NFTs look incredible! The art style is so unique 🎨",
    createdAt: new Date("2024-03-08T17:20:00Z"),
    parentId: undefined,
  },
]

export const mockActivities: Activity[] = [
  {
    id: "1",
    userId: "user-1",
    type: "post_created",
    description: "created a new giveaway",
    postId: "1",
    createdAt: new Date("2024-03-10T10:00:00Z"),
  },
  {
    id: "2",
    userId: "user-2",
    type: "entry_submitted",
    description: "entered a giveaway",
    postId: "1",
    createdAt: new Date("2024-03-11T09:15:00Z"),
  },
  {
    id: "3",
    userId: "user-1",
    type: "contribution_made",
    description: "contributed to a help request",
    postId: "2",
    amount: 100,
    createdAt: new Date("2024-03-09T15:45:00Z"),
  },
  {
    id: "4",
    userId: "user-3",
    type: "post_created",
    description: "created a new giveaway",
    postId: "3",
    createdAt: new Date("2024-03-08T16:45:00Z"),
  },
  {
    id: "5",
    userId: "user-4",
    type: "post_created",
    description: "created a help request",
    postId: "2",
    createdAt: new Date("2024-03-09T14:30:00Z"),
  },
]

export const mockPosts: Post[] = [
  {
    id: "1",
    type: "giveaway",
    authorId: "user-1",
    author: mockUsers[0],
    title: "🎁 $500 USDC Giveaway for New Developers!",
    description:
      "Celebrating our community growth! I'm giving away $500 USDC to help new developers get started. Share your coding journey and what you're building!",
    media: [
      {
        id: "1",
        type: "image",
        url: "/crypto-giveaway-banner.png",
      },
    ],
    createdAt: new Date("2024-03-10T10:00:00Z"),
    updatedAt: new Date("2024-03-10T10:00:00Z"),
    status: "active",
    burnCount: 234,
    shareCount: 89,
    commentCount: 45,
    prizeAmount: 500,
    currency: "USDC",
    winnerCount: 1,
    likesCount: 100,
    entriesCount: 15,
    selectionType: "random",
    entryRequirements: ["Follow @alexchen", "Share your coding story", "Tag 2 friends"],
    proofRequired: false,
    endDate: new Date("2024-03-20T23:59:59Z"),
    entries: mockEntries.filter((e) => e.postId === "1"),
    winners: [],
  },
  {
    id: "2",
    type: "help-request",
    authorId: "user-4",
    author: mockUsers[3],
    title: "🙏 Help Me Get a New Laptop for Coding",
    description:
      "Hi everyone! I'm a computer science student and my old laptop finally gave up. I need help raising funds for a new one to continue my studies and coding projects. Any contribution would mean the world to me!",
    createdAt: new Date("2024-03-09T14:30:00Z"),
    updatedAt: new Date("2024-03-09T14:30:00Z"),
    status: "active",
    burnCount: 156,
    shareCount: 67,
    commentCount: 23,
    targetAmount: 800,
    currentAmount: 245,
    currency: "USDC",
    likesCount: 44,
    entriesCount: 5,
    contributions: mockContributions.filter((c) => c.postId === "2"),
  },
  {
    id: "3",
    type: "giveaway",
    authorId: "user-3",
    author: mockUsers[2],
    title: "🚀 NFT Collection Giveaway - 3 Winners!",
    description:
      'Launching my new NFT collection and want to give back to the community! Giving away 3 exclusive NFTs from the "Future Builders" collection.',
    media: [
      {
        id: "2",
        type: "image",
        url: "/futuristic-nft-collection.png",
      },
    ],
    createdAt: new Date("2024-03-08T16:45:00Z"),
    updatedAt: new Date("2024-03-08T16:45:00Z"),
    status: "active",
    burnCount: 445,
    shareCount: 178,
    commentCount: 92,
    prizeAmount: 3,
    currency: "NFT",
    winnerCount: 3,
    likesCount: 64,
    entriesCount: 4,
    selectionType: "manual",
    entryRequirements: ["Follow @marcusw", "Repost this giveaway", "Show your creative work"],
    proofRequired: true,
    endDate: new Date("2024-03-15T20:00:00Z"),
    entries: mockEntries.filter((e) => e.postId === "3"),
    winners: [],
  },
  {
    id: "4",
    type: "giveaway",
    authorId: "user-2",
    author: mockUsers[1],
    title: "🎨 Design Tutorial Video + Free Resources",
    description:
      "Just dropped my latest design tutorial! Learn advanced Figma techniques and get access to my premium design system. Giving away 5 copies of my complete UI kit to lucky winners!",
    media: [
      {
        id: "3",
        type: "video",
        url: "/design-tutorial-thumbnail.png",
        thumbnail: "/figma-tutorial-thumbnail.png",
      },
    ],
    createdAt: new Date("2024-03-12T08:30:00Z"),
    updatedAt: new Date("2024-03-12T08:30:00Z"),
    status: "active",
    burnCount: 89,
    shareCount: 34,
    commentCount: 18,
    prizeAmount: 5,
    currency: "Digital Assets",
    winnerCount: 5,
    likesCount: 76,
    entriesCount: 7,
    selectionType: "random",
    entryRequirements: ["Watch the full video", "Follow @sarahj", "Share your design work"],
    proofRequired: false,
    endDate: new Date("2024-03-18T23:59:59Z"),
    entries: mockEntries.filter((e) => e.postId === "4"),
    winners: [],
  },
  {
    id: "5",
    type: "help-request",
    authorId: "user-5",
    author: mockUsers[4],
    title: "💚 Mental Health Support - Therapy Sessions",
    description:
      "Hey community, I've been struggling with anxiety and depression lately. I found a great therapist but the sessions are expensive. Any help would be incredibly appreciated. Mental health matters!",
    createdAt: new Date("2024-03-11T09:00:00Z"),
    updatedAt: new Date("2024-03-11T09:00:00Z"),
    status: "active",
    burnCount: 67,
    shareCount: 23,
    commentCount: 15,
    targetAmount: 600,
    currentAmount: 350,
    currency: "USDC",
    likesCount: 59,
    entriesCount: 13,
    contributions: mockContributions.filter((c) => c.postId === "5"),
  },
  {
    id: "6",
    type: "giveaway",
    authorId: "user-5",
    author: mockUsers[4],
    title: "🎮 Ultimate Gaming Setup Showcase + Giveaway",
    description:
      "Finally completed my dream gaming setup! Check out the full tour and enter to win some awesome gaming peripherals. Multiple winners, multiple prizes!",
    media: [
      {
        id: "4",
        type: "image",
        url: "/rgb-gaming-setup.png",
      },
      {
        id: "5",
        type: "image",
        url: "/mechanical-keyboard-and-gaming-mouse.png",
      },
      {
        id: "6",
        type: "video",
        url: "/gaming-setup-tour.png",
        thumbnail: "/placeholder-whvi9.png",
      },
      {
        id: "7",
        type: "image",
        url: "/placeholder-8awlp.png",
      },
    ],
    createdAt: new Date("2024-03-13T10:15:00Z"),
    updatedAt: new Date("2024-03-13T10:15:00Z"),
    status: "active",
    burnCount: 156,
    shareCount: 78,
    commentCount: 42,
    prizeAmount: 4,
    currency: "Gaming Gear",
    winnerCount: 4,
    likesCount: 90,
    entriesCount: 12,
    selectionType: "random",
    entryRequirements: ["Follow @davidk", "Share your gaming setup", "Tag a gaming buddy"],
    proofRequired: false,
    endDate: new Date("2024-03-22T20:00:00Z"),
    entries: mockEntries.filter((e) => e.postId === "6"),
    winners: [],
  },
  {
    id: "7",
    type: "help-request",
    authorId: "user-1",
    author: mockUsers[0],
    title: "📚 Community Learning Resources Fund",
    description:
      "Building a free learning platform for underserved communities. We need funds for hosting, content creation, and educational materials. Every dollar helps someone learn to code!",
    media: [
      {
        id: "8",
        type: "image",
        url: "/placeholder-r9nsr.png",
      },
      {
        id: "9",
        type: "image",
        url: "/coding-bootcamp-classroom.png",
      },
    ],
    createdAt: new Date("2024-03-07T16:20:00Z"),
    updatedAt: new Date("2024-03-07T16:20:00Z"),
    status: "active",
    burnCount: 298,
    shareCount: 145,
    commentCount: 67,
    targetAmount: 2000,
    currentAmount: 1450,
    currency: "USDC",
    likesCount: 87,
    entriesCount: 16,
    contributions: mockContributions.filter((c) => c.postId === "7"),
  },
  {
    id: "8",
    type: "giveaway",
    authorId: "user-3",
    author: mockUsers[2],
    title: "💡 Startup Pitch Competition - Win Mentorship!",
    description:
      "Calling all entrepreneurs! Pitch your startup idea in 60 seconds or less. Winners get 1-on-1 mentorship sessions with successful founders, plus funding opportunities. Let's build the future together!",
    createdAt: new Date("2024-03-06T12:00:00Z"),
    updatedAt: new Date("2024-03-06T12:00:00Z"),
    status: "active",
    burnCount: 189,
    shareCount: 92,
    commentCount: 38,
    prizeAmount: 3,
    currency: "Mentorship Sessions",
    winnerCount: 3,
    likesCount: 71,
    entriesCount: 8,
    selectionType: "manual",
    entryRequirements: ["Submit 60-second pitch video", "Follow @marcusw", "Use hashtag #StartupPitch2024"],
    proofRequired: true,
    endDate: new Date("2024-03-25T23:59:59Z"),
    entries: mockEntries.filter((e) => e.postId === "8"),
    winners: [],
  },
]
